--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jasonsouryamatheshoponcontainers
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: jasonsouryamatheshoponcontainers
  template: 
    metadata: 
      labels: 
        app: jasonsouryamatheshoponcontainers
    spec: 
      containers: 
        - image: devtestcc.azurecr.io/jasonsouryamatheshoponcontainers
          name: jasonsouryamatheshoponcontainers
          ports: ~
        - containerPort: 80
