apiVersion : apps/v1
kind: Deployment
metadata:
  name: jasonsouryamatheshoponcontainers 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jasonsouryamatheshoponcontainers
  template:
    metadata:
      labels:
        app: jasonsouryamatheshoponcontainers 
    spec:
      containers:
        - name: jasonsouryamatheshoponcontainers 
          image: devtestcc.azurecr.io/jasonsouryamatheshoponcontainers
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          ports:
          - containerPort: 80
